---
# tasks file for ansible-role-nginx-controller-license
- name: Fail if required variables are not defined
  assert:
    that: ("{{ item }} is defined") and ("{{ item }} | length > 0")
  with_items:
    - license
    - controller_auth_token
    - controller_fqdn

- name: POST controller license
  uri:
    url: "https://{{controller_fqdn}}/api/v1/platform/license-file"
    method: POST
    body: 
      content: "{{ license }}"
    body_format: json
    return_content: yes
    status_code: 200
    validate_certs: false
    headers:
      Cookie: "{{controller_auth_token}}"
  register: controller_response

- name: GET controller license status
  uri:
    url: "https://{{controller_fqdn}}/api/v1/platform/license"
    method: GET
    status_code: 200
    validate_certs: false
    headers:
      Cookie: "{{controller_auth_token}}"
  register: controller_license
