---
- name: Converge
  hosts: all

  vars:
  #   controller_fqdn: ""
  #   license: ""
  #   user_email: ""
  #   user_password: ""

  tasks:
    - include_role:
        name: ansible_role_nginx_controller_license

  post_tasks:
    - debug:
        msg: "{{ controller_license }}"
